package com.shortsense.service

/**
 * Lightweight AI for Shorts UI detection - makes detection specific to Shorts player only.
 *
 * Problem solved: App was detecting Shorts in home page, long-form videos, comment section.
 * This tiny logistic regression (20 features -> 1 output, ~1KB) distinguishes real Shorts player
 * from other YouTube screens with 95%+ accuracy on synthetic data.
 *
 * Features derived from accessibility tree:
 * - Primary player IDs (reel_watch_fragment_root, reel_recycler, etc.)
 * - Secondary IDs (progress bar, engagement panel, etc.)
 * - Negative signals (shelf IDs, long-form IDs, comment IDs)
 * - Window class and layout features
 *
 * Trained on synthetic UI states simulating real YouTube:
 * - Shorts player: high primary, high secondary, low shelf/longform, fullscreen vertical
 * - Home feed: high shelf, no primary, not fullscreen
 * - Long-form: high longform IDs, no primary, not vertical
 * - Comments: high comment IDs
 *
 * Inference: <0.1ms, no framework, pure Kotlin math.
 * Generated by model/surface_detector.py - do not edit by hand.
 */
object SurfaceDetector {

    // Feature order must match Python training
    private const val FEATURE_COUNT = 20

    // Weights from training - accuracy 100.0% on test set
    private val WEIGHTS = floatArrayOf(
        1.525165f, 1.089635f, 0.790673f, 0.866538f, 0.523639f, 0.232778f, 0.733887f, 0.473756f, 0.363571f, 1.463073f, 0.572281f, 0.526605f, -1.678024f, -1.552098f, 0.019153f, 1.86971f, 1.136608f, 0.014458f, 0.074105f, 0.678271f
    )
    private const val BIAS = -4.088567f

    data class Input(
        val hasPrimaryRoot: Boolean = false,
        val hasReelRecycler: Boolean = false,
        val hasShortsContainer: Boolean = false,
        val hasVerticalFeed: Boolean = false,
        val hasPlayerPageContainer: Boolean = false,
        val hasProgressBar: Boolean = false,
        val hasTimeBar: Boolean = false,
        val hasEngagementPanel: Boolean = false,
        val hasActionBar: Boolean = false,
        val hasPlayerOverlay: Boolean = false,
        val hasShortsPlayerRoot: Boolean = false,
        val numSecondaryIds: Float = 0f,  // 0-1 normalized count
        val numShelfIds: Float = 0f,
        val numLongformIds: Float = 0f,
        val numCommentIds: Float = 0f,
        val windowClassScore: Float = 0f,  // 0=not shorts, 1=maybe, 2=definitely
        val isFullscreenVertical: Boolean = false,
        val hasChannelAvatar: Boolean = false,
        val hasSubscribeButton: Boolean = false,
        val hasSoundRow: Boolean = false
    )

    data class Result(
        val isShorts: Boolean,
        val confidence: Float,  // 0-1
        val logit: Float,
        val reason: String
    )

    fun predict(input: Input): Result {
        val feats = floatArrayOf(
            if (input.hasPrimaryRoot) 1f else 0f,
            if (input.hasReelRecycler) 1f else 0f,
            if (input.hasShortsContainer) 1f else 0f,
            if (input.hasVerticalFeed) 1f else 0f,
            if (input.hasPlayerPageContainer) 1f else 0f,
            if (input.hasProgressBar) 1f else 0f,
            if (input.hasTimeBar) 1f else 0f,
            if (input.hasEngagementPanel) 1f else 0f,
            if (input.hasActionBar) 1f else 0f,
            if (input.hasPlayerOverlay) 1f else 0f,
            if (input.hasShortsPlayerRoot) 1f else 0f,
            input.numSecondaryIds.coerceIn(0f, 1f),
            input.numShelfIds.coerceIn(0f, 1f),
            input.numLongformIds.coerceIn(0f, 1f),
            input.numCommentIds.coerceIn(0f, 1f),
            input.windowClassScore.coerceIn(0f, 2f) / 2f,  // normalize 0-2 to 0-1
            if (input.isFullscreenVertical) 1f else 0f,
            if (input.hasChannelAvatar) 1f else 0f,
            if (input.hasSubscribeButton) 1f else 0f,
            if (input.hasSoundRow) 1f else 0f
        )

        var logit = BIAS
        for (i in 0 until FEATURE_COUNT) {
            logit += WEIGHTS[i] * feats[i]
        }

        val prob = sigmoid(logit)
        val isShorts = prob >= 0.5f

        val reason = buildString {
            append("AI confidence=")
            append(String.format("%.2f", prob))
            append(" (")
            append(if (isShorts) "SHORTS" else "NOT_SHORTS")
            append(") logit=")
            append(String.format("%.2f", logit))
            append(" primary=")
            append(listOf(
                if (input.hasPrimaryRoot) "root" else null,
                if (input.hasReelRecycler) "recycler" else null,
                if (input.hasShortsContainer) "container" else null,
                if (input.hasVerticalFeed) "vertical" else null
            ).filterNotNull().joinToString(","))
            if (input.numShelfIds > 0.3f) append(" shelf=${input.numShelfIds}")
            if (input.numLongformIds > 0.3f) append(" longform=${input.numLongformIds}")
            if (input.numCommentIds > 0.5f) append(" comments=${input.numCommentIds}")
        }

        return Result(isShorts, prob, logit, reason)
    }

    private fun sigmoid(x: Float): Float {
        if (x < -30f) return 0f
        if (x > 30f) return 1f
        return (1.0 / (1.0 + kotlin.math.exp(-x.toDouble()))).toFloat()
    }

    // For debugging - explain which features contributed most
    fun explain(input: Input): List<Pair<String, Float>> {
        val feats = floatArrayOf(
            if (input.hasPrimaryRoot) 1f else 0f,
            if (input.hasReelRecycler) 1f else 0f,
            if (input.hasShortsContainer) 1f else 0f,
            if (input.hasVerticalFeed) 1f else 0f,
            if (input.hasPlayerPageContainer) 1f else 0f,
            if (input.hasProgressBar) 1f else 0f,
            if (input.hasTimeBar) 1f else 0f,
            if (input.hasEngagementPanel) 1f else 0f,
            if (input.hasActionBar) 1f else 0f,
            if (input.hasPlayerOverlay) 1f else 0f,
            if (input.hasShortsPlayerRoot) 1f else 0f,
            input.numSecondaryIds,
            input.numShelfIds,
            input.numLongformIds,
            input.numCommentIds,
            input.windowClassScore / 2f,
            if (input.isFullscreenVertical) 1f else 0f,
            if (input.hasChannelAvatar) 1f else 0f,
            if (input.hasSubscribeButton) 1f else 0f,
            if (input.hasSoundRow) 1f else 0f
        )
        val contributions = mutableListOf<Pair<String, Float>>()
        for (i in 0 until FEATURE_COUNT) {
            val contrib = WEIGHTS[i] * feats[i]
            if (kotlin.math.abs(contrib) > 0.05f) {
                contributions.add(Pair(FEATURES[i], contrib))
            }
        }
        contributions.sortByDescending { kotlin.math.abs(it.second) }
        return contributions.take(6)
    }

    private val FEATURES = arrayOf(
        "has_primary_root", "has_reel_recycler", "has_shorts_container", "has_vertical_feed", "has_player_page_container", "has_progress_bar", "has_time_bar", "has_engagement_panel", "has_action_bar", "has_player_overlay", "has_shorts_player_root", "num_secondary_ids", "num_shelf_ids", "num_longform_ids", "num_comment_ids", "window_class_score", "is_fullscreen_vertical", "has_channel_avatar", "has_subscribe_button", "has_sound_row"
    )
}
