"""
Hand-written borderline cases.

These are the calls that decide whether the app is useful or annoying:
study-motivation edits vs technique tips, "movie explained" vs a film scene,
exam memes vs exam strategy, lab demos vs satisfying slime.

Fields
------
title, channel : what the Accessibility layer would read off the screen
informative    : 1 = keep (study / knowledge / learnable skill), 0 = block
study          : 1 = academic/study-relevant (used by "Study only" mode)
note           : why the label is what it is
"""

HARD_CASES = [
    # ---------- should be KEPT: study ----------
    dict(title="Newton's laws in 60 seconds #physics #jee", channel="Physics Wallah", informative=1, study=1, note="core study"),
    dict(title="integral of x^2 sin x — integration by parts trick", channel="Maths Wallah", informative=1, study=1, note="core study"),
    dict(title="Krebs cycle explained with diagram | NEET 2026", channel="NEETprep", informative=1, study=1, note="core study"),
    dict(title="how to revise a chapter in 20 minutes", channel="Study with Meera", informative=1, study=1, note="study technique"),
    dict(title="active recall vs re-reading — what science says", channel="Topper's Notebook", informative=1, study=1, note="study technique"),
    dict(title="arrhenius equation numericals solved step by step", channel="Chemistry Adda", informative=1, study=1, note="core study"),
    dict(title="binary search on answer — DSA pattern", channel="Take U Forward", informative=1, study=1, note="core study"),
    dict(title="DBMS normalisation 1NF 2NF 3NF in 1 minute", channel="Gate Smashers", informative=1, study=1, note="core study"),
    dict(title="english grammar: when to use has vs have", channel="BBC Learning English", informative=1, study=1, note="language study"),
    dict(title="UPSC prelims: how to read the newspaper", channel="Drishti IAS", informative=1, study=1, note="exam strategy"),
    dict(title="class 10 trigonometry table trick", channel="Magnet Brains", informative=1, study=1, note="core study"),
    dict(title="photosynthesis light reaction animation", channel="Learnohub Class 11", informative=1, study=1, note="core study"),
    dict(title="why does ∫1/x dx = ln x ?", channel="3Blue1Brown", informative=1, study=1, note="maths depth"),
    dict(title="rotational motion: moment of inertia of a disc", channel="IIT Madras Online", informative=1, study=1, note="core study"),
    dict(title="organic chemistry mechanism: aldol condensation", channel="Organic Chemistry Tutor", informative=1, study=1, note="core study"),
    dict(title="how I scored 99 in maths boards — my 30 day plan", channel="Padhaku Vimaan", informative=1, study=1, note="study strategy"),
    dict(title="time complexity of nested loops — big O explained", channel="Neso Academy", informative=1, study=1, note="core study"),
    dict(title="ECG interpretation basics for medical students", channel="Medico Academy", informative=1, study=1, note="professional study"),
    dict(title="spaced repetition schedule that actually works", channel="Study Corner", informative=1, study=1, note="study technique"),
    dict(title="Pomodoro technique for long study hours", channel="Exam Veda", informative=1, study=1, note="study technique"),
    dict(title="NEET biology: nephron function MCQ practice", channel="Aakash Institute", informative=1, study=1, note="core study"),
    dict(title="GATE CSE: paging and virtual memory revision", channel="Knowledge Gate", informative=1, study=1, note="core study"),
    dict(title="Hindi to English translation practice sentences", channel="Spoken English Guru", informative=1, study=1, note="language study"),
    dict(title="Mole concept — 10 numericals in 60 seconds", channel="Doubtnut", informative=1, study=1, note="core study"),
    dict(title="how to make notes for UPSC from NCERT", channel="Sarrthi IAS", informative=1, study=1, note="study strategy"),
    dict(title="permutation combination shortcut for JEE Mains", channel="Vedantu JEE", informative=1, study=1, note="core study"),
    dict(title="SQL joins explained with tables", channel="Apna College", informative=1, study=1, note="core study"),
    dict(title="transformer attention mechanism explained", channel="Krish Naik", informative=1, study=1, note="core study"),
    dict(title="class 12 physics: total internal reflection PYQ", channel="Next Toppers", informative=1, study=1, note="core study"),
    dict(title="how to stop phone addiction while studying", channel="Solution Point", informative=1, study=1, note="study meta-skill"),

    # ---------- should be KEPT: informational / skill ----------
    dict(title="why is the sky blue? #science", channel="Veritasium", informative=1, study=0, note="science explainer"),
    dict(title="how compound interest actually works", channel="CA Rachana Ranade", informative=1, study=0, note="finance literacy"),
    dict(title="what is a repo rate — explained in 60 seconds", channel="Zerodha Varsity", informative=1, study=0, note="finance literacy"),
    dict(title="James Webb telescope just found something strange", channel="NASA Goddard", informative=1, study=0, note="science news"),
    dict(title="why do we get hiccups? | human body", channel="Institute of Human Anatomy", informative=1, study=0, note="health info"),
    dict(title="the geography of the Himalayas explained", channel="Geography Now", informative=1, study=0, note="general knowledge"),
    dict(title="what caused world war 1 in 60 seconds", channel="OverSimplified", informative=1, study=0, note="history"),
    dict(title="how touchscreens work", channel="Real Engineering", informative=1, study=0, note="engineering explainer"),
    dict(title="knife skills every beginner should learn", channel="Your Food Lab", informative=1, study=0, note="practical skill"),
    dict(title="deadlift setup — 3 cues that fix your back", channel="Jeff Nippard", informative=1, study=0, note="practical skill"),
    dict(title="excel vlookup in 60 seconds", channel="Leila Gharani", informative=1, study=0, note="office skill"),
    dict(title="barre chord for absolute beginners", channel="Justin Guitar", informative=1, study=0, note="practical skill"),
    dict(title="CPR steps — what to do in the first 60 seconds", channel="First Aid Basics", informative=1, study=0, note="life skill"),
    dict(title="how UPI payments actually work behind the scenes", channel="ByteByteGo", informative=1, study=0, note="tech explainer"),
    dict(title="the science of sleep and memory", channel="SciShow Psych", informative=1, study=0, note="science"),
    dict(title="why 0.999... equals 1 | maths", channel="Numberphile", informative=1, study=0, note="maths curiosity"),
    dict(title="what if the sun disappeared", channel="Kurzgesagt In a Nutshell", informative=1, study=0, note="science"),
    dict(title="history of the Indus Valley Civilisation", channel="Ancient Americas", informative=1, study=0, note="history"),
    dict(title="how credit scores are calculated in India", channel="Labour Law Advisor", informative=1, study=0, note="finance literacy"),
    dict(title="why antibiotics stop working", channel="Healthcare Triage", informative=1, study=0, note="health info"),
    dict(title="beginner push up form fix", channel="Squat University", informative=1, study=0, note="practical skill"),
    dict(title="photoshop curves explained for beginners", channel="Peter McKinnon", informative=1, study=0, note="creative skill"),
    dict(title="how the stock market index is calculated", channel="Finance with Sharan", informative=1, study=0, note="finance literacy"),
    dict(title="chandrayaan landing — what the mission found", channel="ISRO Official", informative=1, study=0, note="science news"),
    dict(title="why earthquakes happen — plate tectonics", channel="PBS Eons", informative=1, study=0, note="science"),

    # ---------- should be BLOCKED: entertainment ----------
    dict(title="when the teacher leaves the class 😂", channel="Funny Comedy Squad", informative=0, study=0, note="comedy"),
    dict(title="POV: exam tomorrow and you started today", channel="Meme Factory India", informative=0, study=0, note="exam meme, no knowledge"),
    dict(title="wait for the last ball 🔥", channel="Cricket Highlights Zone", informative=0, study=0, note="sports highlights"),
    dict(title="new song 2026 lyrical video", channel="T-Series", informative=0, study=0, note="music"),
    dict(title="insane 1v4 clutch", channel="BGMI Highlights", informative=0, study=0, note="gaming"),
    dict(title="my morning routine vlog 🌸", channel="Sourav Joshi Vlogs", informative=0, study=0, note="vlog"),
    dict(title="movie ending explained in Hindi", channel="Movie Explained Hindi", informative=0, study=0, note="entertainment explainer"),
    dict(title="best fight scene ever 🎬", channel="Movie Scenes HD", informative=0, study=0, note="movie clip"),
    dict(title="sigma rule no 1 🔥🔥", channel="Sigma Motivation Hindi", informative=0, study=0, note="motivational edit, no content"),
    dict(title="gym motivation status 4k", channel="Beast Mode Motivation", informative=0, study=0, note="motivation edit"),
    dict(title="celebrity spotted at airport 😱", channel="Celeb Gossip Daily", informative=0, study=0, note="gossip"),
    dict(title="satisfying slime compilation", channel="Oddly Satisfying", informative=0, study=0, note="asmr/satisfying"),
    dict(title="5 minute craft with glue gun 🤩", channel="5 Minute Crafts", informative=0, study=0, note="craft hack"),
    dict(title="street food tour in Delhi 😋", channel="Street Food Frenzy", informative=0, study=0, note="food vlog"),
    dict(title="outfit of the day 💅", channel="Fashion Lookbook", informative=0, study=0, note="fashion"),
    dict(title="tarot reading for your zodiac 🔮", channel="Tarot Reading Live", informative=0, study=0, note="astrology"),
    dict(title="sure shot prediction today 💰", channel="Betting Tips Pro", informative=0, study=0, note="betting"),
    dict(title="new reel trend dance 🔥", channel="Team Naach", informative=0, study=0, note="dance"),
    dict(title="trying viral food challenge", channel="Mukbang India", informative=0, study=0, note="eating show"),
    dict(title="bhagya ka khel — emotional story", channel="Emotional Story Hindi", informative=0, study=0, note="status story"),
    dict(title="tiktok compilation 2026", channel="Trending Now India", informative=0, study=0, note="compilation"),
    dict(title="gta 5 stunt gone wrong", channel="Techno Gamerz", informative=0, study=0, note="gaming"),
    dict(title="big boss latest drama", channel="Bollywood Updates", informative=0, study=0, note="gossip"),
    dict(title="hair styling hack you need", channel="Beauty Glow Tips", informative=0, study=0, note="beauty"),
    dict(title="24 hour challenge in my new house", channel="Flying Beast", informative=0, study=0, note="challenge vlog"),
    dict(title="physical transformation 💪", channel="Gym Motivation Beast", informative=0, study=0, note="fitness edit"),
    dict(title="roast of the year 😂", channel="Roast Central", informative=0, study=0, note="roast"),
    dict(title="crypto pump signal — 100% working", channel="Crypto Signals Pro", informative=0, study=0, note="trading hype"),
    dict(title="my first time watching this scene", channel="Reaction King", informative=0, study=0, note="reaction"),
    dict(title="viral video of the day", channel="Viral Video Daily", informative=0, study=0, note="viral clip"),

    # ---------- tricky look-alikes ----------
    dict(title="aaj ka rashifal — mithun", channel="Astrology Rashi Today", informative=0, study=0, note="astrology disguised as info"),
    dict(title="class 10 board exam meme 😂", channel="Meme Factory India", informative=0, study=0, note="mentions exam but is a meme"),
    dict(title="study motivation status for students", channel="Success Quotes Daily", informative=0, study=0, note="motivation status, no teaching"),
    dict(title="IAS interview question: gk", channel="InfoBytes India", informative=1, study=1, note="real gk content"),
    dict(title="funny physics teacher moment", channel="Vigyan Recharge", informative=0, study=0, note="re-labelled: a 'funny moment' on an edu channel is entertainment, no knowledge content"),
    dict(title="physics of a football free kick", channel="Physics Girl", informative=1, study=0, note="applied science"),
    dict(title="how to solve any coding problem", channel="NeetCode", informative=1, study=1, note="method"),
    dict(title="roadmap to become a data analyst in 2026", channel="CampusX Machine Learning", informative=1, study=0, note="career guidance, not academic - re-labelled study=0"),
    dict(title="salary of a doctor in India — reality check", channel="Doctor's Study Room", informative=1, study=0, note="career info, not academic - re-labelled study=0"),
    dict(title="dance tutorial for beginners", channel="Pranit Dance", informative=1, study=0, note="learnable skill"),
    dict(title="guitar lesson: your first song", channel="Guitar Zero to Hero", informative=1, study=0, note="learnable skill"),
    dict(title="my gym routine — full week plan", channel="Fitness with Anurag", informative=1, study=0, note="learnable skill"),
    dict(title="my skincare routine for glowing skin", channel="Beauty Glow Tips", informative=0, study=0, note="product lifestyle"),
    dict(title="top 10 cringe moments 2026", channel="Cringe Compilation", informative=0, study=0, note="compilation"),
    dict(title="how to edit reels like a pro", channel="Skillshare Sessions", informative=1, study=0, note="learnable skill"),
    dict(title="cricket bowling action analysis — biomechanics", channel="Sports Science Lab", informative=1, study=0, note="analysis, knowledge"),
    dict(title="last over world cup final highlights", channel="Star Sports Clips", informative=0, study=0, note="highlights"),
    dict(title="what is quantum entanglement — simple explanation", channel="MinutePhysics", informative=1, study=0, note="science"),
    dict(title="gaming setup tour 2026", channel="Gadget Review India", informative=0, study=0, note="consumer tour"),
    dict(title="new iphone unboxing beast 😍", channel="Tech Unboxing Beast", informative=0, study=0, note="unboxing"),
    dict(title="how a semiconductor fab works — explained", channel="Asianometry", informative=1, study=0, note="engineering info"),
    dict(title="biryani recipe in 60 seconds", channel="Hebbars Kitchen", informative=1, study=0, note="cooking skill"),
    dict(title="5 tricks for faster mental maths", channel="Numerical Ninja", informative=1, study=1, note="study skill"),
    dict(title="why you forget what you study — memory", channel="Big Think", informative=1, study=1, note="learning science"),
    dict(title="class 11 physics one shot full chapter", channel="Physics Wallah", informative=1, study=1, note="lecture clip"),
    dict(title="how toppers use instagram without wasting time", channel="Padhai Ka Funda", informative=1, study=1, note="study meta"),
    dict(title="sigma edit with study motivation 🔥", channel="Mood Edits", informative=0, study=0, note="edit with study keyword bait"),
    dict(title="teacher vs student funny skit", channel="Triggered Insaan", informative=0, study=0, note="skit"),
    dict(title="free fire new season update", channel="Free Fire India", informative=0, study=0, note="game update"),
    dict(title="interview with an IAS topper about strategy", channel="Vision IAS", informative=1, study=1, note="exam strategy"),
    dict(title="actor's workout transformation 2026", channel="Entertainment Tonight India", informative=0, study=0, note="celebrity fitness"),
    dict(title="how the RBI controls inflation", channel="Economics Explained", informative=1, study=0, note="economics"),
    dict(title="motivational speech that will change your life", channel="Dream Big Speaker", informative=1, study=0, note="motivational talk: the user counts this as informative"),
    dict(title="calculus in 100 seconds", channel="3Blue1Brown", informative=1, study=1, note="maths"),
    dict(title="why planes don't fall — lift explained", channel="Real Engineering", informative=1, study=0, note="engineering"),
    dict(title="how much do youtubers earn", channel="Technical Guruji Vlogs", informative=1, study=0, note="informational, business"),
    dict(title="barber reaction to funny haircut 😂", channel="Reaction King", informative=0, study=0, note="reaction"),
    dict(title="government job vacancy update — last date", channel="Adda247", informative=1, study=1, note="exam/job info"),
    dict(title="sarkari naukri ke liye best books", channel="Study IQ Education", informative=1, study=1, note="study resource"),
    dict(title="bhootiya kahani raat ke liye", channel="Emotional Story Hindi", informative=0, study=0, note="horror story"),
    dict(title="why do we dream? sleep science", channel="SciShow", informative=1, study=0, note="science"),
    dict(title="dubai travel vlog — 7 days in 60 seconds", channel="Wanderlust Shots", informative=0, study=0, note="travel vlog"),
    dict(title="learn 100 english words in 3 minutes", channel="English with Lucy", informative=1, study=1, note="language"),
    dict(title="trading vs investing — difference explained", channel="CA Parag Gupta", informative=1, study=0, note="finance literacy"),
    dict(title="sure shot jackpot trick 💰", channel="Jackpot Trick Official", informative=0, study=0, note="gambling"),
    dict(title="friction — why we don't slip while walking", channel="Sabine Hossenfelder", informative=1, study=1, note="physics"),
    dict(title="best duet song cover on reels", channel="Punjabi Beats", informative=0, study=0, note="music cover"),
    dict(title="how to answer 'tell me about yourself'", channel="Skillshare Sessions", informative=1, study=0, note="career skill, not academic - re-labelled study=0"),
    dict(title="caste census explained — what it means", channel="ThePrint", informative=1, study=0, note="news explainer"),
    dict(title="cringe love story part 3", channel="Emotional Story Hindi", informative=0, study=0, note="story serial"),
    dict(title="free body diagram basics", channel="Neso Academy", informative=1, study=1, note="physics"),
    dict(title="asmr keyboard typing for sleep", channel="ASMR Relaxing Sounds", informative=0, study=0, note="asmr"),
    dict(title="what is the 5G spectrum auction", channel="Wendover Productions", informative=1, study=0, note="explainer"),
    dict(title="how to draw a perfect circle freehand", channel="DIY Creators", informative=1, study=0, note="skill"),
    dict(title="viral horse dancing video 😂", channel="Funny Animals TV", informative=0, study=0, note="viral animal clip"),
    dict(title="revision checklist for JEE aspirants", channel="Marathon Academy", informative=1, study=1, note="study"),
    dict(title="types of engineering branches — which one to pick", channel="Aman Dhattarwal", informative=1, study=1, note="career study"),
    dict(title="gym fail compilation 2026", channel="Gym Motivation Beast", informative=0, study=0, note="fail compilation"),
    dict(title="what is dark matter?", channel="PBS Space Time", informative=1, study=0, note="physics explainer"),
    dict(title="emotional song for broken heart status", channel="Sad Status Video", informative=0, study=0, note="status song"),
    dict(title="how to type faster on keyboard", channel="Kevin Stratvert", informative=1, study=0, note="productivity skill"),
    dict(title="top 5 gaming phones under 30000", channel="Gadget Review India", informative=0, study=0, note="re-labelled: shopping listicle, not knowledge"),
    dict(title="instagram reels editing transition tutorial", channel="Peter McKinnon", informative=1, study=0, note="creative skill"),
    dict(title="funny waiter prank 😂😂", channel="Prank King", informative=0, study=0, note="prank"),
    dict(title="how vaccines train your immune system", channel="Kurzgesagt In a Nutshell", informative=1, study=0, note="science"),
    dict(title="exam paper leak news update", channel="Exam Fear", informative=1, study=1, note="exam info"),
    dict(title="satisfying hydraulic press crushing things", channel="Hydraulic Press Channel", informative=0, study=0, note="satisfying"),
    dict(title="python for beginners — day 1", channel="CodeWithHarry", informative=1, study=1, note="study"),
    dict(title="how to remember everything you read", channel="Topper's Notebook", informative=1, study=1, note="study technique"),
    dict(title="college fest dance performance 🔥", channel="Mumbiker Nikhil", informative=0, study=0, note="performance"),
    dict(title="organic farming method explained", channel="Down to Earth", informative=1, study=0, note="info"),
    dict(title="bike stunt gone wrong", channel="Viral Video Daily", informative=0, study=0, note="stunt"),

    # ---------- the definition the user actually asked for ----------
    # kept: PCM / competitive problem solving
    dict(title="JEE Advanced 2023 problem on projectile motion — solved", channel="Physics Wallah", informative=1, study=1, note="PCM problem"),
    dict(title="can you solve this mole concept question?", channel="Chemistry Adda", informative=1, study=1, note="PCM problem"),
    dict(title="how to find the last two digits of 7^77 — number theory", channel="Maths Wallah", informative=1, study=1, note="PCM problem"),
    dict(title="NEET physics: two blocks and a pulley numerical", channel="NEETprep", informative=1, study=1, note="PCM problem"),
    # kept: motivation that teaches a method, not a grindset edit
    dict(title="how to stay consistent when you do not feel like studying", channel="Study Corner", informative=1, study=1, note="study motivation with a method"),
    dict(title="why motivation fades and what actually works", channel="Practical Psychology", informative=1, study=0, note="psychology of motivation"),
    dict(title="the 2 minute rule for beating procrastination", channel="Topper's Notebook", informative=1, study=1, note="study technique"),
    dict(title="self discipline is a skill — here is how to train it", channel="Big Think", informative=1, study=0, note="self-improvement"),
    dict(title="lessons from Ratan Tata's life for young founders", channel="Think School", informative=1, study=0, note="story with lessons"),
    # kept: history, politics and civics
    dict(title="how a bill becomes a law in India", channel="Bharat Explained", informative=1, study=1, note="civics"),
    dict(title="Article 370 explained in 60 seconds", channel="ThePrint", informative=1, study=1, note="polity"),
    dict(title="Lok Sabha vs Rajya Sabha — what is the difference", channel="Study IQ Education", informative=1, study=1, note="polity"),
    dict(title="why the Battle of Plassey changed India", channel="History of India", informative=1, study=1, note="history"),
    dict(title="the Indus Valley city planning nobody talks about", channel="Ancient India Explained", informative=1, study=1, note="history"),
    dict(title="what the Election Commission actually does", channel="Soch by Mohak Mangal", informative=1, study=1, note="civics"),
    # kept: new ideas, inventions and how things work
    dict(title="how the zipper was invented", channel="Today I Found Out", informative=1, study=0, note="invention story"),
    dict(title="why startups fail — 5 reasons founders miss", channel="Think School", informative=1, study=0, note="business idea"),
    dict(title="how UPI moved India's money", channel="Wendover Productions", informative=1, study=0, note="systems explainer"),
    dict(title="the engineering behind a jet engine", channel="Real Engineering", informative=1, study=0, note="engineering"),
    # blocked: adult and racy content
    dict(title="hot photoshoot behind the scenes 🔥", channel="Celeb Gossip Daily", informative=0, study=0, note="adult clickbait"),
    dict(title="nude model shoot leaked", channel="Viral Video Daily", informative=0, study=0, note="adult"),
    dict(title="bikini try on haul", channel="Fashion Lookbook", informative=0, study=0, note="adult-adjacent haul"),
    dict(title="sexy song scene hd", channel="Movie Scenes HD", informative=0, study=0, note="racy clip"),
    dict(title="adult comedy skit 😂", channel="Funny Comedy Squad", informative=0, study=0, note="adult comedy"),
    dict(title="bold scene from new web series", channel="Bollywood Updates", informative=0, study=0, note="racy clip"),
    # blocked: memes and grindset edits dressed up as motivation
    dict(title="top 10 memes of the week 😂", channel="Meme Factory India", informative=0, study=0, note="meme compilation"),
    dict(title="sigma grindset motivation edit", channel="Sigma Motivation Hindi", informative=0, study=0, note="motivational edit that teaches nothing"),
    dict(title="gym motivation status — no excuses", channel="Beast Mode Motivation", informative=0, study=0, note="hype edit"),
]

def stats():
    n = len(HARD_CASES)
    inf = sum(c["informative"] for c in HARD_CASES)
    stu = sum(c["study"] for c in HARD_CASES)
    return {"n": n, "informative": inf, "entertainment": n - inf, "study": stu}


if __name__ == "__main__":
    print(stats())
