package com.shortsense

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.database.MatrixCursor
import android.net.Uri
import android.os.ParcelFileDescriptor
import android.provider.OpenableColumns
import java.io.File
import java.io.FileNotFoundException

/**
 * Hands the exported log to whichever app the user picks in the share sheet.
 *
 * This is a hand-written file provider rather than `androidx.core.content.FileProvider`
 * because the app deliberately carries no AndroidX dependency. It exposes exactly one
 * directory ([LogExporter.DIR]) inside the app's private files, read-only, with
 * `exported="false"` and per-URI grants, so nothing else is reachable and nothing is public.
 */
class ExportProvider : ContentProvider() {

    companion object {
        const val AUTHORITY = "com.shortsense.exports"

        /** Names are generated by [LogExporter], so anything else is a path-traversal attempt. */
        private val SAFE_NAME = Regex("""[A-Za-z0-9._-]{1,120}""")

        fun uriFor(file: File): Uri = Uri.parse("content://$AUTHORITY/${file.name}")
    }

    private fun fileFor(uri: Uri): File {
        val name = uri.lastPathSegment.orEmpty()
        if (!SAFE_NAME.matches(name)) throw FileNotFoundException("not an export: $name")
        val dir = File(requireNotNull(context).filesDir, LogExporter.DIR)
        return File(dir, name)
    }

    override fun onCreate(): Boolean = true

    override fun getType(uri: Uri): String = "text/plain"

    override fun openFile(uri: Uri, mode: String): ParcelFileDescriptor {
        if (mode != "r") throw FileNotFoundException("read-only provider")
        val file = fileFor(uri)
        if (!file.isFile) throw FileNotFoundException(uri.toString())
        return ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_ONLY)
    }

    override fun query(
        uri: Uri,
        projection: Array<out String>?,
        selection: String?,
        selectionArgs: Array<out String>?,
        sortOrder: String?
    ): Cursor {
        val file = fileFor(uri)
        if (!file.isFile) throw FileNotFoundException(uri.toString())
        val columns = projection ?: arrayOf(OpenableColumns.DISPLAY_NAME, OpenableColumns.SIZE)
        val cursor = MatrixCursor(columns, 1)
        val row = cursor.newRow()
        for (column in columns) {
            when (column) {
                OpenableColumns.DISPLAY_NAME -> row.add(file.name)
                OpenableColumns.SIZE -> row.add(file.length())
                else -> row.add(null)
            }
        }
        return cursor
    }

    override fun insert(uri: Uri, values: ContentValues?): Uri? = null
    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0
    override fun update(
        uri: Uri,
        values: ContentValues?,
        selection: String?,
        selectionArgs: Array<out String>?
    ): Int = 0
}
