package com.shortsense

import java.io.File

/**
 * Unit tests need three files that live outside the app module: the trained model, its
 * metadata, and the fixture that proves Kotlin and Python agree. Gradle runs tests with
 * the module directory as the working directory, but that is an implementation detail, so
 * resolve by searching upward instead of assuming a path.
 */
object RepoFiles {

    private val candidates = listOf(
        "",                     // running from the repo root
        "..",                   // running from android/
        "../..",                // running from android/app/
        "../../..",
        "../../../..",
    )

    fun find(relative: String): File? {
        for (prefix in candidates) {
            val f = if (prefix.isEmpty()) File(relative) else File(prefix, relative)
            if (f.isFile) return f
        }
        return null
    }

    fun require(relative: String): File =
        find(relative) ?: error(
            "could not find '$relative'. Run the tests from the repository (the model and " +
                "the parity fixture are generated by 'python3 model/train.py')."
        )

    val keywordsAsset: File get() = require("android/app/src/main/assets/keywords.txt")
    val modelBin: File get() = require("model/model.bin")
    val modelMeta: File get() = require("model/model.meta")
    val parityFixture: File get() = require("model/parity.txt")
}
