package com.shortsense.nlp

/**
 * Feature extraction. This is a hand-written mirror of `model/features.py` and the two
 * must agree byte for byte, because the model was trained in Python and runs here.
 *
 * The contract is enforced by `ParityTest`, which replays a fixture generated by
 * `python3 model/train.py` (see `model/parity.txt`) and asserts that this file produces
 * the same feature list and the same probabilities. If you change anything here, retrain
 * and rerun that test - do not "fix" one side only.
 */
object Features {

    private val SUFFIXES = arrayOf("ingly", "edly", "ies", "ied", "ing", "ed", "ly", "es")
    private val MULTI_SPACE = Regex(" +")

    /** Keep letters, marks and numbers of any script; everything else becomes a space. */
    private fun keep(ch: Char): Boolean {
        if (Character.isLetterOrDigit(ch)) return true
        // Python keeps every Unicode category starting with L, M or N. isLetterOrDigit
        // covers L* and Nd/Nl; these add the combining marks (which is what keeps
        // Devanagari matras intact) and the "other number" category (superscripts etc).
        return when (Character.getType(ch)) {
            Character.NON_SPACING_MARK.toInt(),
            Character.COMBINING_SPACING_MARK.toInt(),
            Character.ENCLOSING_MARK.toInt(),
            Character.OTHER_NUMBER.toInt() -> true
            else -> false
        }
    }

    fun normalize(text: String): String {
        if (text.isEmpty()) return ""
        val sb = StringBuilder(text.length)
        for (ch in text.lowercase()) {
            sb.append(if (keep(ch)) ch else ' ')
        }
        return MULTI_SPACE.replace(sb.toString(), " ").trim()
    }

    /** Light suffix stripper; identical table and order to features.py:stem(). */
    fun stem(word: String): String {
        if (word.length > 5) {
            for (suf in SUFFIXES) {
                if (word.endsWith(suf) && word.length - suf.length >= 3) {
                    var base = word.substring(0, word.length - suf.length)
                    if (suf == "ies" || suf == "ied") base += "y"
                    return base
                }
            }
        }
        if (word.length > 4 && word.endsWith("s") && !word.endsWith("ss")) {
            return word.substring(0, word.length - 1)
        }
        return word
    }

    private fun tokens(normalized: String): List<String> =
        if (normalized.isEmpty()) emptyList() else normalized.split(' ')

    /**
     * All features for one Short. Sorted, because the fixture and the tests compare lists.
     */
    fun features(title: String, channel: String?, lex: Lexicon): List<String> {
        val chan = channel ?: ""
        val tnorm = normalize(title)
        val cnorm = normalize(chan)
        val ttok = tokens(tnorm)
        val ctok = tokens(cnorm)
        val feat = HashSet<String>(64)

        for (w in ttok) {
            if (w.length >= 2) feat.add("w:$w")
        }
        for (w in ctok) {
            if (w.length >= 2) feat.add("w:$w")
        }

        for (w in ttok + ctok) {
            if (w.length >= 2) {
                val s = stem(w)
                if (s.length >= 2) {
                    feat.add("st:$s")
                    if (lex.infoStems.contains(s)) {
                        feat.add("k:i:$s")
                    } else if (lex.entStems.contains(s)) {
                        feat.add("k:e:$s")
                    }
                }
            }
        }

        // channel *type* signal: works for channels the model has never seen
        for (w in ctok) {
            val s = stem(w)
            if (lex.chanInfoStems.contains(s)) {
                feat.add("ch:i:$s")
            } else if (lex.chanEntStems.contains(s)) {
                feat.add("ch:e:$s")
            }
        }

        for (i in 0 until ttok.size - 1) {
            feat.add("b:${ttok[i]}_${ttok[i + 1]}")
        }

        for (w in ttok) {
            for (n in intArrayOf(3, 4)) {
                if (w.length >= n) {
                    for (i in 0..w.length - n) {
                        feat.add("c$n:" + w.substring(i, i + n))
                    }
                }
            }
            if (w.length >= 2) feat.add("p2:" + w.substring(0, 2))
            if (w.length > 3) feat.add("s3:" + w.substring(w.length - 3))
        }

        if (tnorm.isNotEmpty()) {
            val padded = " $tnorm "
            for (p in lex.infoPhrases) {
                if (padded.contains(" $p ")) feat.add("ph:i:" + p.replace(' ', '_'))
            }
            for (p in lex.entPhrases) {
                if (padded.contains(" $p ")) feat.add("ph:e:" + p.replace(' ', '_'))
            }
        }

        if (ttok.isEmpty()) feat.add("__empty")
        if (ctok.isEmpty()) feat.add("__nochan")
        if (title.any { it.code > 127 }) feat.add("__nonascii")

        return feat.sorted()
    }
}
