package com.shortsense.nlp

import android.content.Context
import java.io.BufferedReader

/**
 * The style lexicon (which words suggest teaching, which suggest entertainment) plus the
 * UI-noise words used when reading the screen.
 *
 * It is read from `assets/keywords.txt`, a file generated by `model/keywords.py`. The
 * app never hard-codes these lists: the trainer and the app therefore cannot drift apart,
 * and the model report always describes exactly the lexicon that ships.
 */
class Lexicon(
    val infoStems: Set<String>,
    val entStems: Set<String>,
    val noiseWords: Set<String>,
    val chanInfoStems: Set<String>,
    val chanEntStems: Set<String>,
    val infoPhrases: List<String>,
    val entPhrases: List<String>
) {

    companion object {
        const val ASSET_NAME = "keywords.txt"

        fun load(context: Context): Lexicon =
            context.assets.open(ASSET_NAME).bufferedReader().use { parse(it) }

        fun parse(reader: BufferedReader): Lexicon {
            val info = HashSet<String>()
            val ent = HashSet<String>()
            val noise = HashSet<String>()
            val chanInfo = HashSet<String>()
            val chanEnt = HashSet<String>()
            val infoPhrases = ArrayList<String>()
            val entPhrases = ArrayList<String>()

            reader.forEachLine { raw ->
                val line = raw.trim()
                if (line.isEmpty() || line.startsWith("#")) return@forEachLine
                val parts = line.split('\t')
                when (parts[0]) {
                    "info" -> if (parts.size > 1) info.add(Features.stem(parts[1]))
                    "ent" -> if (parts.size > 1) ent.add(Features.stem(parts[1]))
                    "noise" -> if (parts.size > 1) noise.add(parts[1])
                    "chaninfo" -> if (parts.size > 1) chanInfo.add(Features.stem(parts[1]))
                    "chanent" -> if (parts.size > 1) chanEnt.add(Features.stem(parts[1]))
                    "phrase" -> if (parts.size > 2) {
                        if (parts[1] == "info") infoPhrases.add(parts[2]) else entPhrases.add(parts[2])
                    }
                }
            }
            return Lexicon(
                info, ent, noise, chanInfo, chanEnt,
                infoPhrases.sorted(), entPhrases.sorted()
            )
        }
    }

    /** True when the text is UI chrome rather than a title (Like, Share, 1.2M views...). */
    fun isUiNoise(text: String): Boolean {
        val t = text.trim().lowercase()
        if (t.isEmpty()) return true
        if (noiseWords.contains(t)) return true
        if (VIEW_COUNT.containsMatchIn(t)) return true
        if (TIME_AGO.containsMatchIn(t)) return true
        if (t.length <= 2) return true
        if (t.all { !it.isLetterOrDigit() }) return true
        return false
    }

    private val VIEW_COUNT = Regex("^[\\d.,]+\\s*(k|m|b|thousand|million|billion|views?|likes?)")
    private val TIME_AGO = Regex("^\\d+\\s*(s|m|h|d|w|y|sec|secs|min|mins|hour|hours|day|days|week|weeks|month|months|year|years)(\\s+ago)?$")
}
