package com.shortsense.nlp

import android.content.Context
import java.io.InputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sqrt

/**
 * Tiny semantic embedding model for Option A - improves accuracy while staying lightweight.
 *
 * This is NOT a full LLM, but a 2MB embedding model that gives semantic understanding:
 * - Vocab: 3000 most frequent words, Dim: 32, Size: ~217KB
 * - Training: Supervised embeddings - learns INFO vs ENT + co-occurrence
 * - Inference: <5ms, pure Kotlin, no framework
 * - Gives semantic understanding: "physics" close to "quantum", "meme" close to "comedy"
 *
 * How it improves accuracy:
 * - Adds semantic cluster features (20 clusters)
 * - Adds info/ent similarity features
 * - Better generalization to unseen words via embeddings
 * - Still lightweight: 217KB vs 600MB for TinyLlama
 *
 * Generated by model/tiny_embedding.py - do not edit by hand.
 */
class SemanticModel private constructor(
    private val vocab: HashMap<String, Int>,
    private val embeddings: ShortArray,
    private val scale: Int,
    private val dim: Int,
    private val centroids: Array<FloatArray>,
    private val infoCentroid: FloatArray,
    private val entCentroid: FloatArray
) {

    fun embedWord(word: String): FloatArray? {
        val idx = vocab[word] ?: return null
        val base = idx * dim
        val out = FloatArray(dim)
        for (d in 0 until dim) {
            out[d] = embeddings[base + d].toFloat() / scale
        }
        return out
    }

    fun embedText(text: String): FloatArray {
        val tokens = Features.normalize(text).split(' ').filter { it.length >= 2 }
        if (tokens.isEmpty()) return FloatArray(dim)
        val acc = FloatArray(dim)
        var count = 0
        for (tok in tokens) {
            val emb = embedWord(tok) ?: continue
            for (d in 0 until dim) {
                acc[d] = acc[d] + emb[d]
            }
            count++
        }
        if (count > 0) {
            for (d in 0 until dim) {
                acc[d] = acc[d] / count
            }
        }
        return acc
    }

    fun cosineSimilarity(a: FloatArray, b: FloatArray): Float {
        var dot = 0f
        var normA = 0f
        var normB = 0f
        for (d in 0 until dim) {
            dot += a[d] * b[d]
            normA += a[d] * a[d]
            normB += b[d] * b[d]
        }
        if (normA == 0f || normB == 0f) return 0f
        return dot / (sqrt(normA) * sqrt(normB))
    }

    fun semanticCluster(embedding: FloatArray): Int {
        var best = 0
        var bestDist = Float.MAX_VALUE
        for (ci in centroids.indices) {
            var dist = 0f
            for (d in 0 until dim) {
                val diff = embedding[d] - centroids[ci][d]
                dist += diff * diff
            }
            if (dist < bestDist) {
                bestDist = dist
                best = ci
            }
        }
        return best
    }

    fun infoScore(embedding: FloatArray): Float {
        // Positive = INFO-like, Negative = ENT-like
        val simInfo = cosineSimilarity(embedding, infoCentroid)
        val simEnt = cosineSimilarity(embedding, entCentroid)
        return simInfo - simEnt
    }

    fun semanticFeatures(title: String, channel: String): List<String> {
        val text = "$title $channel"
        val emb = embedText(text)
        if (emb.all { it == 0f }) return emptyList()
        
        val cluster = semanticCluster(emb)
        val infoScore = infoScore(emb)
        
        val feats = mutableListOf<String>()
        feats.add("sem_cluster:$cluster")
        // Quantize info score into buckets
        val bucket = when {
            infoScore > 0.3f -> "high_info"
            infoScore > 0.1f -> "med_info"
            infoScore > -0.1f -> "neutral"
            infoScore > -0.3f -> "med_ent"
            else -> "high_ent"
        }
        feats.add("sem_bucket:$bucket")
        // Add info score as feature with threshold
        if (infoScore > 0.2f) feats.add("sem_info_pos")
        if (infoScore < -0.2f) feats.add("sem_ent_pos")
        return feats
    }

    companion object {
        const val ASSET_NAME = "semantic.bin"
        private const val MAGIC = "SEMB"

        fun load(context: Context): SemanticModel =
            context.assets.open(ASSET_NAME).use { load(it) }

        fun load(stream: InputStream): SemanticModel {
            val bytes = stream.readBytes()
            val buf = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
            val magic = ByteArray(4)
            buf.get(magic)
            require(String(magic, Charsets.US_ASCII) == MAGIC) { "not a semantic model" }
            val version = buf.short.toInt() and 0xFFFF
            require(version == 1)
            val vocabSize = buf.short.toInt() and 0xFFFF
            val dim = buf.short.toInt() and 0xFFFF
            val scale = buf.int
            val numClusters = buf.short.toInt() and 0xFFFF
            
            val centroids = Array(numClusters) { FloatArray(dim) }
            for (ci in 0 until numClusters) {
                for (d in 0 until dim) {
                    centroids[ci][d] = buf.float
                }
            }
            val infoCent = FloatArray(dim)
            for (d in 0 until dim) infoCent[d] = buf.float
            val entCent = FloatArray(dim)
            for (d in 0 until dim) entCent[d] = buf.float
            
            val vocab = HashMap<String, Int>(vocabSize * 2)
            val embeddings = ShortArray(vocabSize * dim)
            for (i in 0 until vocabSize) {
                val len = buf.get().toInt() and 0xFF
                val wb = ByteArray(len)
                buf.get(wb)
                val word = String(wb, Charsets.UTF_8)
                vocab[word] = i
                val base = i * dim
                for (d in 0 until dim) {
                    embeddings[base + d] = buf.short
                }
            }
            return SemanticModel(vocab, embeddings, scale, dim, centroids, infoCent, entCent)
        }
    }
}
