plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    // One fixed debug key, committed on purpose: GitHub runners generate a fresh debug
    // keystore every time, which would mean uninstalling the app before every update.
    // This is a debug-only key with the well known "android" password - not a secret.
    signingConfigs {
        create("shortsense") {
            storeFile = rootProject.file("debug.keystore")
            storeType = "PKCS12"
            storePassword = "android"
            keyAlias = "shortsense"
            keyPassword = "android"
        }
    }

    namespace = "com.shortsense"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.shortsense"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("shortsense")
        }
        release {
            // the app ships as a debug-signed (installable) build from CI; see README
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    // Deliberately no AndroidX: the app is small, and fewer dependencies means a faster,
    // more reliable build (and one less supply chain to trust for something whose whole
    // selling point is "nothing leaves your phone").
    testImplementation("junit:junit:4.13.2")
}

// The model artifacts live in ../model (repo root) and are generated by
// `python3 model/train.py`. Copying them at build time means the APK can never ship a
// stale model while the .bin in git says otherwise.
val syncModelArtifacts = tasks.register<Copy>("syncModelArtifacts") {
    from(rootProject.file("../model/model.bin"))
    from(rootProject.file("../model/model.json"))
    into(project.layout.projectDirectory.dir("src/main/assets"))
    doFirst { logger.lifecycle("ShortsSense: syncing model artifacts from ../model") }
}

tasks.matching { it.name == "preBuild" }.configureEach { dependsOn(syncModelArtifacts) }
